repo:
  name: "The Not WP Repository"
  home: https://notwp.org
  desc: "A collection of themes and plugins for WordPress, hosted by the community"
  role: 
    producer: 1
    consumer_source: https://notwp.org
  news:
    - https://www.thewpcommunitycollective.com/feed/

# change producer to 0 to product a mirror of the 'consumer_source' target

