repo:
  name: "The Not WP Repository"
  home: https://notwp.org
  desc: "A collection of themes and plugins for WordPress, hosted by the community"
  image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGNvbW11bml0eXxlbnwwfHwwfHx8MA%3D%3D"
  addons:
    image: "https://images.unsplash.com/photo-1607705703571-c5a8695f18f6?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjZ8fGNvZGV8ZW58MHx8MHx8fDA%3D"
  role: 
    producer: 0
    consumer_source: https://notwp.org
  news:
    num: 8
    sites:
      - https://www.thewpcommunitycollective.com/feed/
      - https://techcrunch.com/search/wordpress/feed/rss2/

